version: '3'
services:
 db:
   image: mysql:latest
   container_name: student_sync_db
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=student_sync_db
   volumes:
     - ./db:/var/lib/mysql 